services:
  - type: web
    name: ai-code-analysis-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://YOUR-VERCEL-APP-NAME.vercel.app